spring.application.name=veloxdb

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/veloxdb?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server
server.port=8080
# Slow query log path
veloxdb.slow-query-log-path=D:/veloxdb/slow_query.log

# Enable scheduling
spring.task.scheduling.pool.size=5